#Q1. What is the total revenue generated by male vs. female customers?
SELECT gender,SUM(purchase_amount) as revenue
from mytable
group by gender
order by gender;

#Q2. Which customers used a discount but still spent more than the average purchase amount? 
SELECT customer_id,purchase_amount
FROM mytable
WHERE discount_applied='Yes' and purchase_amount >= (SELECT AVG(purchase_amount) from mytable);

#Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, ROUND(AVG(review_rating),2) as "Average Product Rating"
from mytable
group by item_purchased
order by avg(review_rating) desc
limit 5;

#Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
select shipping_type,ROUND(AVG(purchase_amount),2)
from mytable
where shipping_type in ('Standard','Express')
group by shipping_type;

#Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT subscription_status,COUNT(customer_id) as total_customers,
ROUND(AVG(purchase_amount),2) as average_spend,
ROUND(SUM(purchase_amount),2) as total_revenue
FROM mytable
group by subscription_status;

#Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
round(100*sum(case when discount_applied = 'Yes' then 1 else 0 end )/count(*),2) as discount_rate
from mytable
group by item_purchased
order by discount_rate desc
limit 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
with customer_type as (
SELECT customer_id,previous_purchases,
case 
	when previous_purchases =1 then 'New'
    when previous_purchases between 2 and 10 then 'Returning'
    else 'Loyal'
    end as customer_segment
from mytable)

select customer_segment,count(*) as 'Number of Customers'
from customer_type
group by customer_segment;

-- Q8. What are the top 3 most purchased products within each category? 
with items as (
SELECT category,
	item_purchased,
	count(customer_id) as total_orders,
	row_number() over (partition by category order by count(customer_id) desc) as item_rank
from mytable
group by category,item_purchased
)
select item_rank,category,item_purchased,total_orders 
from items
where item_rank <=3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
		count(customer_id) as repeat_buyers
from mytable 
where previous_purchases > 5
group by subscription_status;

-- Q10. What is the revenue contribution of each age group? 
select age_group,sum(purchase_amount) as total_revenue
from mytable
group by age_group
order by total_revenue desc;
		